In [10]:
f=open('C:/Users/Asus/Desktop/HATE.txt')

In [11]:
lines=f.readlines()
text=[]
y=[]
for line in lines:
    w=line.lower().strip().split(',')
    text.append(w[0])
    l=0
    if w[1]=='pos':
        l=1
    y.append(l)
print(text)
print(y)

['i love you', 'i hate you', 'i kill you', 'i love to kill you', 'i admire you']
[1, 0, 0, 0, 1]


In [13]:
from sklearn.feature_extraction.text import CountVectorizer
vec=CountVectorizer()
vec.fit(text)
v=vec.transform(text).toarray()
print(vec,v)   

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None) [[0 0 0 1 0 1]
 [0 1 0 0 0 1]
 [0 0 1 0 0 1]
 [0 0 1 1 1 1]
 [1 0 0 0 0 1]]


In [3]:
def tfidf(text):
    from sklearn.feature_extraction.text import TfidfVectorizer
    vec=TfidfVectorizer()
    vec.fit(text)
    v=vec.transform(text).toarray()
    return v
x=tfidf(text)
print(x)

[[0.         0.         0.         0.861037   0.         0.50854232]
 [0.         0.90275015 0.         0.         0.         0.43016528]
 [0.         0.         0.861037   0.         0.         0.50854232]
 [0.         0.         0.50733821 0.50733821 0.62883263 0.29964212]
 [0.90275015 0.         0.         0.         0.         0.43016528]]


In [4]:
print(y)

[1, 0, 0, 0, 1]


In [14]:
def tfidf(x):
    from sklearn.feature_extraction.text import TfidfVectorizer
    vec=TfidfVectorizer()
    vec.fit(text)
    v=vec.transform(text).toarray()
    return v

In [15]:
tfidf(text)

array([[0.        , 0.        , 0.        , 0.861037  , 0.        ,
        0.50854232],
       [0.        , 0.90275015, 0.        , 0.        , 0.        ,
        0.43016528],
       [0.        , 0.        , 0.861037  , 0.        , 0.        ,
        0.50854232],
       [0.        , 0.        , 0.50733821, 0.50733821, 0.62883263,
        0.29964212],
       [0.90275015, 0.        , 0.        , 0.        , 0.        ,
        0.43016528]])

In [17]:
print(y)

[1, 0, 0, 0, 1]


In [19]:

from sklearn.tree import DecisionTreeClassifier

In [20]:
model=DecisionTreeClassifier()
model.fit(x,y)#x=input feacture,y lable(actual)
ycap=model.predict(x)
print(y)#actual(lable)
print(ycap)#(predication)

[1, 0, 0, 0, 1]
[1 0 0 0 1]


In [22]:
import numpy as np
y=np.array(y)
ycap=np.array(ycap)
y==ycap

array([ True,  True,  True,  True,  True])

In [23]:
import numpy as np
def accuracy (y,ycap):
    y=np.array(y)
    ycap=np.array(ycap)
    c=y==ycap
    pcent=c[c==True].size
    n=y.size
    all=pcent/n*100
    return all

In [24]:
accuracy(y,ycap)

100.0

In [25]:
yy=np.c_[y]

In [26]:
print(yy)

[[1]
 [0]
 [0]
 [0]
 [1]]


In [27]:
from numpy.linalg import inv
beta=inv(x.T.dot(x)).dot(x.T.dot(yy))
beta.shape

(6, 1)

In [28]:
print(beta)

[[ 1.   ]
 [-0.125]
 [-0.5  ]
 [ 1.125]
 [-0.625]
 [ 0.75 ]]


In [29]:
def logistic(x,b):
    return 1/(1+np.exp(x.dot(b)))
yycap=logistic(x,beta)
print(yycap)

[[0.20585838]
 [0.44774644]
 [0.51227547]
 [0.46286909]
 [0.22699209]]


In [30]:
yycap[yycap>0.5]=1
yycap[yycap<0.5]=0
print(yycap)

[[0.]
 [0.]
 [1.]
 [0.]
 [0.]]


In [31]:
print(yy)

[[1]
 [0]
 [0]
 [0]
 [1]]


In [32]:
accuracy(yy,yycap)

40.0